# Generated by Django 3.0.8 on 2020-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20200903_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default='solo-slug'),
            preserve_default=False,
        ),
    ]
