name: Development Workflow - Testing

on:
  push:
    branches: [ master, dev, 'issue-*', 'feature/*' ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Firefox
      run: |
        sudo apt-get install firefox
    
    - name: Start remote selenium server
      run: |
        chmod +x .github/scripts/selenium.sh
        ./.github/scripts/selenium.sh
    
    - name: Run Tests
      run: |
        cd jmad
        python manage.py test solos
        python manage.py test jmad
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
        DEBUG: ${{secrets.DEBUG}}
